Laravel-Backpack/docs

- 3.4/crud-tutorial.md
When the tutorial is telling how to add the model's 'name' field to the controller, it is using addFields instead of addField   ('s' needs removed)
> Typo: addField instead of AddFields in crud-tutorial.md

- 3.4/getting-started-advanced-features.md
The links under "Additionally, here are a few more ways you can customize your CRUDs:" were missing their forward slashes at the start, causing the links to land at 404s.
> Added missing / causing broken links

- 3.4/crud-fields.md
"readonly" doesn't work outside the "attributes"
> Moving the "readonly" and "disabled" into the attributes

- 3.5/crud-fields.md
**File**: src / PanelTraits / Fields.php
before v3.4.39 had:  
`checkIfFieldIsFirstOfItsType( $field, $fields_array )`
v3.4.39 and later (inc. v3.5):  
`checkIfFieldIsFirstOfItsType( $field )`
**Result**: Removed second parameter from 3.5-docs example
> removed unused parameter from 3.5

- 3.5/crud-buttons.md
The button name is 'update', not 'edit'.
```
$this->crud->removeButton('edit', 'line');      // this doesn't remove the button
$this->crud->removeButton('update', 'line');    // this does
```
> Fix wrong name of 'edit' button on the 'line' stack

- 4.0/getting-started-license-and-support.md
Avoids confusion with payment currency.
> Use euro symbols instead of dollars

- 4.0/upgrade-guide.md
It seems I put the last edit in the wrong place, leading ot the CrudController heading to be in the middle of the Routes steps. This fixes that.
> Corrected position of CrudController header

- 4.0/crud-operations.md
- 4.0/upgrade-guide.md
The routes generated have lost their `crud.` prefix.
I believe this happened in v4 - I can't see it having changed in other recent versions.
> CRUD routes no longer have the crud. prefix

- 4.0/crud-tutorial.md
Removes the Admin namespace, because right now the url would be Admin\Admin\TagCrudController which is not what you want!
> Fixes syntax error in the crud tutorial page

- 4.0/crud-fields.md
The way backpack is designed, when an upload field is present and required if you submit a form without uploading the file an empty field is going to validate and fail ofcourse in the required rule. 
If you submit the form and everything is correct the process will be smooth, until you edit that entity.
When editing an entry if the upload field value is present (user already sent one file with success) we will just re-create the fancy file preview and not the upload field. If user submits the form without changing anything and we are not using **sometimes|required**, the validation will fail, as we are not sending any upload field in request. Here comes the power of [sometimes laravel validation rule](https://laravel.com/docs/5.8/validation#conditionally-adding-rules) that will not …
> Clarify about upload field validation rules.

- 4.0/crud-buttons.md
Hi,
I have fixed the example code of `addButtonFromView` in crud-buttons.md
This was explaining about `\Backpack\CRUD\app\Library\CrudPanel\Traits\Buttons::addButton` not `\Backpack\CRUD\app\Library\CrudPanel\Traits\Buttons::addButtonFromView`.
Thanks,
> Fixed arguments of addButtonFromView

- 4.0/crud-columns.md
I have been really struggling to find out a way to make an absolute path for images columns since I host my images in an s3 bucket, and it took me too long looking at the docs and in the internet trying to find a way to do that but I didn't. Finally, I decided to go to columns/image.blade.php and make my changes there, but it was surprising to me when I figured that there is already an option that you can add to the image field which is ```disk``` and it does exactly what I wanted but this wasn't mentioned in the docs, that's why I decided to add it there in case anyone was looking to do the same thing.
> add extra param to the image column

- 4.0/crud-how-to.md
Docs have a bad command stated. 
```
$ php artisan backpack:crud:publish buttons/create                                            
There are no commands defined in the "backpack:crud" namespace.  
Did you mean this?                                               
backpack                                                     
$ php artisan backpack:publish buttons/create
Cannot find source view file at vendor/backpack/crud/src/resources/views/buttons/create.blade.php - make sure you've picked an existing view file
```
> Fixed publish command

- 4.0/crud-buttons.md
- 4.1/crud-buttons.md
Hi,
Since I have reported an issue #78, following section of `crud-buttons.md` is broken.
https://backpackforlaravel.com/docs/4.0/crud-buttons#adding-a-custom-button-with-javascript-to-the-top-stack
I have fixed it adding a line break and tested it on the [online demo](https://parsedown.org/extra/) of `erusev/parsedown-extra`.
I hope it helps people who is reading the page.
Thanks,
> Fixed broken section in crud-buttons.md

- 4.0/crud-operations.md
If I'm right (I've following the tuto), you need the $id parameter in the publish method to keep it related to the route where $id is present.
For someone who is mastering Laravel I think it's clear, but maybe you could, somewhere, add a note about putting parameters in route <=> public function ACTION($parameter)
Also, cherry on the cake, maybe a generator with optional parameter like
```
php artisan backpack:crud-operation --params=id Comment
php artisan backpack:crud-operation --params=key1,key2 Comment
```
2nd version to match composed primary key maybe
Thanks for the good work again.
> Adding $id parameter in "publish"

- 4.1/crud-fields.md
The 'name' of page_or_link field is somewhat misleading as it does not update the page_id or link fields.
> page_or_link name field

- 4.0/crud-operation-list-entries.md
Buttons are refered as "add" and "edit" but are named "create" and "update" in code.
> Using correct button names in buttons section

- 4.1/crud-fluent-syntax.md
When using `select` field type it requires an attribute. Without it you receive an error: _Undefined index: attribute_
> Select Field Requires 'attribute'

- 4.1/crud-operation-update.md
Make it clear that Backpack's Sluggable always saves the slug as JSON, ignoring the translatable property.
> Backpack's Sluggable saves as JSON

- 3.4/crud-columns.md
- 3.5/crud-columns.md
- 3.6/crud-columns.md
- 4.0/crud-columns.md
- 4.1/crud-columns.md
After scratching my head for a while trying to figure out why date formats in my CRUD list view were not working as expected, I dove into the code and discovered that the Blade template that formats the columns is calling ```Carbon::isoFormat()``` rather than ```Carbon::format()``` (which I had been using elsewhere).  This changes the format strings that must be used.  
This patch simply adds a  note about this and provides a link to the Carbon docs describing the available format specifiers for ```isoFormat()```.
> Add note to date and datetime CRUD column documentation re: ISO formats

- 4.1/crud-fields.md
Apparently the 'image' field no longer uses the 'upload' attribute. At least the corresponding view 'image.blade.php' does not make use of it anymore.
> Removed obsolete upload attribute from image field

- 3.4/crud-columns.md
- 3.5/crud-columns.md
- 3.6/crud-columns.md
- 4.0/crud-columns.md
- 4.1/crud-columns.md
Backticks changed to apostrophes in code examples
> Backticks changed to apostrophes in code examples

- 4.1/crud-fields.md
hasMany() relationship in Laravel refers to 1-n and doesn't require pivot table. While updating and creating hasMany() relationship in your model, this should be handled manually as explained in 'https://github.com/Laravel-Backpack/CRUD/issues/3031#issuecomment-660034201'. Referring this method through the documentation is misleading and better to be removed in my opinion.
There is also a relationship mentioned belongsToOne() which doesn't exist in Laravel core, removed this as well.
> Misleading hasMany() relationship.

- 4.1/crud-fields.md
I believe category was for the non-multiple select ajax example. I am also assuming it should be in the singular.
> Change 'category' to 'city'

- 4.1/crud-fields.md
- 4.1/crud-operation-fetch.md
While trying the hasMany relationship, I realized that the select was not populated:
The logs shown an error 500: `"POST /admin/proyecto/fetch/tareas HTTP/1.1" 500 84`
Problem was App\Models was concatenated to namespace so it needs a heading backslash. :+1:  So other people don't have to spend some time figuring it out.
Also, when I read the documentation, maybe because English is not my first language, I misunderstood. After examples of not-ajax and ajax, where it says:
> Then, you need to create the route and method that allows select2 to search and fetch the results...
I misunderstood and though that only the ajax example needed the fetch operation. Maybe you could change it to:
> In both cases, you need to create the route and method that allows select2 to search and fetch the …
> Problem with namespace in fetch operation

- 4.1/crud-cheat-sheet.md
- 4.1/crud-fields.md
- 4.1/crud-filters.md
- 4.1/crud-operation-create.md
- 4.1/crud-operation-list-entries.md
- 4.1/crud-operations.md
The way to access the request from a controller [has changed in version 4.1](https://backpackforlaravel.com/docs/4.1/upgrade-guide#step-11) but the change has not been reflected to all docs. This PR updates docs to use the new getter.
`$this->request` and `$this->crud->request` to `this->crud->getRequest()`
> Update for $this->crud->getRequest()

- 4.1/installation.md
Since https://github.com/Laravel-Backpack/CRUD/pull/3241 was merged, I think the docs need to be updated too. 
Update installation text to tell backpack users to update `User` model in config if they are using Laravel 8 and up.
> Update installation text for Laravel 8 users

- 4.1/crud-filters.md
When we use **_select2_multiple_** filter (if the query for each element should use `orWhere`, in the third parameter of the addFilter() method.) with another filter **_select2_**
1. If we filter with one value in both filter it's working perfectly
2. But if we use one value in **_select2_** filter and more than one value in **_select2_multiple_** filter then it didn't working correctly.
So for this problem if we use `whereIn` then it's working every scenarios and i guess it's best option as well
More than that there is no point to use `where` in the **_select2_multiple_**
I change from:
To:
> Corrected select2_multiple filter information

- 4.1/crud-operations.md
fixing multiple mistakes in the **Creating a New Operation With An Interface** instructions
- `request()->ajax()` not `$crud->request->ajax()` (_Cannot access protected property Backpack\CRUD\app\Library\CrudPanel\CrudPanel::$request_)
- `protected function setupCloneDefaults()` not `protected setupCloneDefaults()`
> Fix Creating a New Operation With An Interface

- 4.1/crud-fields.md
added both examples because the image shows the `stock` editor and the one with options defined is slightly different.
> Add summer editor options example

- 4.1/add-ons-tutorial-using-the-addon-skeleton.md
Fixes #207. I'll copy-paste the issue here so that we can close it:
So I've created [this thing](https://github.com/DigitallyHappy/backpack-addon-skeleton). This addon skeleton should allow backpackers to create add-ons a lot more easily, basically without even thinking about how packages are supposed to work, because if the files are in the correct place, they'll just be loaded by the `AddonServiceProvider` we're built.
So basically the process would be:
- code in your own project
- use [laravel-packager](https://github.com/Jeroen-G/laravel-packager) to create a new package, and use [our skeleton](https://github.com/DigitallyHappy/backpack-addon-skeleton) as a template there;
- move the files into the package;
- create a Github repo and push the changes;
- put it up on Packagist;
- …
> [WIP] Add tutorial for creating Backpack add-ons using our own skeleton

- 4.1/crud-fields.md
Given example is not clearly indicating that every option in the plugin can be used.
I've tried to include more real life example where theme colors can be defined with swatches. Also included a link to plugin's docs so users can check further options available.
> Update color_picker field example

- 4.1/crud-fields.md
I had problem with SQL error, that image attribute doesn't have default value when seeding my my table. For example:
$obj = new \App\Models\Product();
$obj->name = 'name';
$obj->image = 'image path';
$obj->save();
> Set image attribute when creating new class object

- 4.1/crud-buttons.md
"after_javascript" is referenced in the documentation, although the
examples use "after_scripts".
The first doesn't work, the last does.
> Change "after_javascript" for "after_scripts"

- 4.1/crud-fields.md
Documentation for fakes was confusing because after some testing I came up finding out that for translatable attributes to work as fakes they can't be in `$casts`.
> Update fakes documentation for translatable attributes

- 4.1/crud-fields.md
In 4.1, this else would make the image save as `https://blabla.com/uploads/image.jpg` in the database instead of the expected `uploads/image.jpg` when you edit an entry and don't change image field.
> Remove breaking else

- 4.2-dev/crud-fields.md
- 4.2-dev/crud-how-to.md
This PR:
- adds docs for all functionality inside the `relationship` field in 4.2 (including `hasOne` which wasn't coded yet);
- adds examples for each relationship type inside the CRUD FAQ page (not 100% happy with these but we can polish later);
- renames `fields` and `pivotFields` for `relationship` and `repeatable` into `subfields`;
@pxpm please take note of this naming change. I'm 99% sure `subfields` is a better name for this:
- it makes clear that you're talking about fields inside another field;
- it's general enough to be used by both `repeatable` and `relationship`;
- it's general enough to be used both when defining `pivotFields` and fields on a related entry;
- it fixes the confusing `CRUD::field('relationship')->fields([])` definition that I hadn't noticed;
- it not only …
> renamed fields and pivotFields to subfields; added MUCH clearer docs for relationship field

- 4.2-dev/base-how-to.md
- Fixed the path to `custom-backpack-bundle.css` to be aligned with mix instructions
- Fixed the path segment from `sass` to `scss` to pair with mix instructions
> Small fixes to customize colors doc

- 4.1/crud-save-actions.md
added `save_and_preview` to save actions
Same fix should be done in 4.2-dev doc
> Missing one of default actions

- 5.x/crud-operations.md
I think it can ben confusing or can lead to copy-paste problems to use Admin/Operations namespace in one example and Admin/CustomOperations in another.
Furthermore, the generator does it in Admin/Operations namespace.
I might have missed something too in the doc logic but I don't think so.
> Remove "Custom" in namespaces

- 5.x/crud-fields.md
as the title says, updates the tiny mce documentation. I also think that we should change the image to show the "default" tinymce state, because in the image we show a tinymce instance with extra plugins and custom toolbar etc. That migth lead the users to wrongly think that what is shown is what they will get without aditional configurations. I let that up for you to decide @tabacitu 
Cheers!
> fix tinymce documentation

- 5.x/crud-how-to.md
- 5.x/upgrade-guide.md
I replaced the ocurrences of `strippedRequest` with the invokable instead of closure.
I removed option 1 from `unchangeable-crud-field` because that option is not appropriate for that example. Added invokable as an option too.
> add invokable stripRequest to docs

- 5.x/crud-fields.md
- 5.x/crud-how-to.md
Fix for https://github.com/Laravel-Backpack/CRUD/issues/4471.
Rephrased the "How to add a relationship field that depends on another field", to include a reference to the `relationship` field.
Also added a note to suggest the usage of `POST` method.
> Suggested method POST for when using `include_all_form_fields`

- 5.x/crud-how-to.md
I can't believe we don't already have this covered by the docs. I've just added the same thing I wrote in [this StackOverflow post](https://stackoverflow.com/questions/72989432/when-installing-backpack-pro-v5-i-get-a-failed-to-download-backpack-pro-error/72989433#72989433). Hopefully between the two... people who search will get a clear answer.
> add installation error to docs

- 5.x/crud-save-actions.md
This PR adds the missing documentation about how to disable action change notification, as mentioned in Laravel-Backpack/CRUD#4477.
> Add action change notification documentation

- 5.x/crud-buttons.md
Instances of examples with icons that use fa and the fa- prefix replaced with those of la and la- respectively.
> Reflect migration to Line Awesome in examples

- 3.6/crud-fields.md
The old link: https://laravel.com/docs/9.x/eloquent-mutators#attribute-casting does not exist anymore.
> Replace attribute casting doc with a new link

- 5.x/crud-operation-clone.md
- 5.x/crud-operation-delete.md
When using bulk actions in a `CrudController` developer should know that the bulk check box is added inside the first column, because of that fact he must be aware that the first column should be visible in the table, and also that it could not contain any anchor because bulk checkbox disables all clicks in that row.
> Add notes to docs about bulk actions.

- 5.x/crud-fluent-syntax.md
The PR for ti can be seen [here](https://github.com/Laravel-Backpack/CRUD/pull/5035).
> [Feature] Conditionable trait

- 6.x/upgrade-guide.md
This should prevent the mistake we did by keeping the old config from `base.php` when creating the `ui.php` file.
> Improve config section in v6 upgrade guide

- 6.x/crud-columns.md
Four columns were left to upload on this PR
[Add v6 columns to the docs.](https://github.com/Laravel-Backpack/docs/pull/437)
It's already merged now so created another for the left columns.
- browse_multiple ✅
- icon_picker✅
- repeatable✅
- checklist_dependency❌ // create another issue where we will cover this. 
https://github.com/Laravel-Backpack/CRUD/issues/5143
> Add Left Columns to Docs

- 6.x/crud-columns.md
@tabacitu please merge this PR & close https://github.com/Laravel-Backpack/CRUD/issues/5143
> Add checklist_dependency column to docs

- 6.x/upgrade-guide.md
This was reported in https://github.com/Laravel-Backpack/CRUD/issues/5170
If you ran `composer update` with this class still in config, the `dump-autoload` process would raise an error.
> remove cache busting string

- 6.x/crud-tutorial.md
On the backpack installation I have just installed, the correct name of this file is:
` resources/views/vendor/backpack/ui/inc/menu_items.blade.php`
I am using Laravel Framework 10.14.1 and Backpack/crud 6.03 and backpack/theme-tabler 1.0.2
I am not aware if this is simply a mistake or the old filename.
> Update blade filename

- 6.x/base-components.md
I think "widget type" is wrong here as this page is all about components. The Widget page mentions overriding "widget types".
> Replace incorrect phrase "widget type" with "component"

- 6.x/crud-fields.md
The snippet makes it clear what the code should look like. 
Instead of "forget", the words "omit" or "don't specify" are clearer and better. I suggest "don't specify".
I thought of adding a screenshot, but I am not sure that it is necessary.
> Correct/improve English and add example snippet

- 6.x/base-widgets.md
The description of the div widget was not immediately clear to me, so after experiments to see how the widget worked, I added an explanation for clarification.
> Add an example to explanation of div widget and fix typos

- 6.x/upgrade-guide.md
Solves https://github.com/Laravel-Backpack/CRUD/issues/5187
`No hint path defined for [backpack] `
`@extends(backpack_user() && (Str::startsWith(\Request::path(), config('backpack.base.route_prefix'))) ? 'backpack::layouts.top_left' : 'backpack::layouts.plain')`
Remove old error views.
> Add step to upgrade guide to remove error views.

- 6.x/crud-uploaders.md
I was sure I added this somewhere in the docs ... but can't seem to find.
I think because we thought about engineering a solution that wouldn't avoid this step for the users. 
Maybe we add it in future, but for now I've documented it.
> add docs about file deletion in uploaders

- 6.x/upgrade-guide.md
Solves https://github.com/Laravel-Backpack/docs/issues/474
I upgraded my project and found that the URL `admin/elfinder` started throwing **500**.
```
No hint path defined for [backpack]. {"view":{"view":"/home/bulkmake/public_html/resources/views/vendor/elfinder/elfinder.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): No hint path defined for [backpack]. at /home/bulkmake/public_html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112)
```
```
rm -rf resources/views/vendor/elfinder
php artisan backpack:filemanager:install
```
Do this as a LAST step. And make it more general. _For any add-ons you might have upgraded, please double-check if they have an upgrade guide. For example, elFinder needs you to do …
> V6 upgrade-guide: steps required for filemanager

- 6.x/crud-uploaders.md
This are the docs for https://github.com/Laravel-Backpack/CRUD/pull/5243
> add note about uploaders in relationships

- 6.x/crud-fields.md
Solves https://github.com/Laravel-Backpack/docs/issues/487
A user requested to put the missing `attribute` in the pivotSelect example of the relationship field.
This `attribute` allows users change the `display value`
The attribute is present in other relationship field examples except for pivotSelect.
- [Basic Example](https://backpackforlaravel.com/docs/6.x/crud-fields#relationship-pro)✅
- [Ajax Example](https://backpackforlaravel.com/docs/6.x/crud-fields#load-entries-from-ajax-calls-using-the-fetch-operation-1)✅
- [PivotSelect Example](https://backpackforlaravel.com/docs/6.x/crud-fields#configuring-the-pivot-select-field)❌
> Add `attribute` in relationship field pivot select example

- 6.x/crud-filters.md
I've spent quite a bit of time rewriting this page, so that:
- it uses the fluent syntax
- it is simpler to read and understand
I need help TESTING the docs here. I need someone to use the code I provided in an app, and make sure it's working they're all working expected.
@karandatwani92 can you help with that please?
-- 
Addresses a small part of https://github.com/Laravel-Backpack/docs/issues/450
> make filter docs use fluent syntax by default

- 6.x/crud-filters.md
> replace $this->crud->addClause by CRUD::addClause

- 6.x/crud-columns.md
The documentation stated that the "default_date_format" and "default_datetime_format" are located in /config/backpack/base.php when in reality they are in /config/backpack/ui.php
> Fix file reference in 6.x crud-columns

- 6.x/base-how-to.md
Docs for https://github.com/Laravel-Backpack/CRUD/pull/5301
> add email validation

- 6.x/base-how-to.md
I am trying to make more evident that there are some Framework strings that are not translated by Backpack and that we recommend our users to use https://github.com/Laravel-Lang/lang that has most if not all of that strings translated.
> make more evident that backpack does not translate all the strings

- 6.x/crud-uploaders.md
this was reported in https://github.com/Laravel-Backpack/CRUD/issues/5394
We didn't have "clear" docs on how to use uploaders in custom fields.
> add docs for uploaders in custom fields

- 6.x/base-themes.md
- 6.x/crud-operation-list-entries.md
Hi,
I make this PR because I think it's kinda hard to find out how can we prevent users before they access the page, then I think it's a good idea to add documentation about the access and permission to every Operation.
Currently, I'm working on a new project and using the latest version of backpack, and I found that when I use
```php
CRUD::denyAccess('list');
```
and not adding this code right after ``` CRUD::denyAccess('list'); ```
```php
abort(403, 'You dont have permission to access this page'); 
```
it will show you this error
but when I use this full code
```php
CRUD::denyAccess('list');
abort(403, 'You dont have permission to access this page'); 
```
It works properly, idk if I miss something, let me know if I did something wrong, thank you
also if you agree with this idea, I will …
> Add documentation about access and permission

- 6.x/crud-fields.md
In circumstances where the default Backpack field implementation is not accessible to screen readers and other assistive technologies (and in the absence of any movement on the related bug report (https://github.com/Laravel-Backpack/community-forum/issues/206), I propose to at least actively document and highlight the way to work around this for most of the common field types.   
Note, this would apply to earlier versions as well, but in case there is some need to change the wording I have currently only put this into the 6.x branch.
This, of course, does not ensure accessibility of all field types, but it is better than having no access at all to even basic fields.
> Add aria-label example to Crud Fields documentation (for accessibility)

- 6.x/crud-filters.md
This comes from client:
'2024-01-21 00:00:00'
'2024-01-29 23:59:59'
we don't need to concat 23:59:59
> wrong example for daterange

- 6.x/crud-filters.md
Adds guide to:
- Pass options via `date_range_options`
- how to enable time picker for `date_range` filter.
> Enables time picker for date_range filter

- 6.x/crud-operation-trash.md
It was not clear to developers what happen when they disabled the trash filter. https://github.com/Laravel-Backpack/community-forum/discussions/866
> add note about disabling trashed filter

- 6.x/introduction.md
Fix typos and make minor edits
Both addon and add-ons was used in this file, and probably add-on with a hyphen is the better option to use. For example, see [add-on on Wikipedia](https://en.wikipedia.org/wiki/Add-on)
I added a semi-colon to a bullet point for consistency (as the other three bullet points had semi-colons already). However, it is probably acceptable not to use any punctuation at all in bullet points as it just makes writing documentation more simple.
The ... are not necessary and can be removed.
> Fix typos and make minor edits

- 6.x/getting-started-advanced-features.md
Fix typos and make minor edits.
I removed the semi-colons from the bullet points as most of the bullet points here did not have semi-colons.
I removed the old-fashioned smiley : -) as it looks a little bit odd.
I also noticed that the links to BulkDelete and BulkClone are to the top of the page whereas they could be linked to the particular section.
Also, it appears that the three links at the end for the Custom CRUDs are broken. I think the anchors on the target page have probably changed.
> Fix typos and make minor edits.

- 5.x/crud-operation-trash.md
- 6.x/crud-operation-trash.md
The example usage for `bulkTrash` contains the parameter `$id`, which causes errors when copy-pasted from the docs, like:
```
Too few arguments to function App\Http\Controllers\Admin\UserCrudController::bulkTrash(), 0 passed in ...
```
Updating the sample code block to `bulkTrash()` from `bulkTrash($id)` resolved the error.
> Fix sample bulkTrash usage where parameter should not be provided.

- 6.x/crud-fields.md
Related with https://github.com/Laravel-Backpack/PRO/pull/250.
> Added docs for `select2_json_from_api`

- 6.x/base-how-to.md
- 6.x/crud-how-to.md
- 6.x/demo.md
- 6.x/installation.md
- 6.x/introduction.md
this does a little bit of cleanup and adds mentions of Laravel 11 alongside Laravel 10.
> cleanup and mention laravel 11

- 6.x/crud-fields.md
Add an how to section to `select2_json_api` field, on how one can achieve the scenario of storing only the "id" in the database instead of json object with the id in it.
> add how to docs

- 6.x/base-how-to.md
This are the docs for: https://github.com/Laravel-Backpack/CRUD/pull/5552
> add how to publish the mobile headers

- 6.x/faq.md
fixes https://github.com/Laravel-Backpack/docs/issues/564
> update faq - remove publish commands from docs

- 6.x/crud-columns.md
- 6.x/crud-fields.md
docs for https://github.com/Laravel-Backpack/CRUD/pull/2951
> add group docs

- 6.x/crud-operation-update.md
This are the docs for https://github.com/Laravel-Backpack/CRUD/pull/5563
> add eager load docs to update operation

- 6.x/crud-fields.md
docs for: https://github.com/Laravel-Backpack/CRUD/pull/5650
> add options to checklist_dependency field

- 6.x/crud-operation-list-entries.md
docs for: https://github.com/Laravel-Backpack/CRUD/pull/5655
> re-word details row to accept widgets

- 6.x/crud-operation-list-entries.md
Docs for: https://github.com/Laravel-Backpack/CRUD/pull/5667
> update line buttons docs

- 6.x/crud-operation-update.md
fix small typos on the update operation docs.
> fix typos in update operation

- 6.x/crud-operation-reorder.md
docs for: https://github.com/Laravel-Backpack/CRUD/pull/5677
> allow customizing reorder column names

- 6.x/crud-operation-list-entries.md
change `exportOnlyField` to `exportOnlyColumn`
because in `vendor/backpack/crud/src/resources/views/crud/list.blade.php` the attribute name is `exportOnlyColumn`
and here is the code on your repo 
https://github.com/Laravel-Backpack/CRUD/blob/b58f971aa0f0064f5070ae51f90249d9675c2d50/src/resources/views/crud/list.blade.php#L71-L78
> Fix `exportOnlyColumn` attribute in `crud-operation-list-entries`

- 6.x/crud-filters.md
docs for https://github.com/Laravel-Backpack/PRO/pull/280 and https://github.com/Laravel-Backpack/CRUD/pull/5675
> add debounce filter docs

- 6.x/crud-how-to.md
- 7.x-dev/crud-how-to.md
Remove ambiguity when explaining operation routes. We point to the complete docs from the faq. Not removed for reference.
> remove ambiguous extra route reference

- 7.x-dev/crud-fields.md
This removes the docs for both fields, and point to the packages readme on how to use them.
> Remove ckeditor and tinymce from docs

- 6.x/faq.md
I create a guide with the steps to deploy a Backpack project to Prod.
> add deploy to production

- 6.x/crud-fields.md
- 7.x-dev/crud-fields.md
This adds a note to the google fields about what API's should be selected when generating a key. Also an important note to restrict the key to the application domain when in production. 
Done for both v6 and v7 docs.
> add note about key requirements

- 6.x/crud-operation-fetch.md
- 7.x-dev/crud-operation-fetch.md
docs for: https://github.com/Laravel-Backpack/PRO/pull/315
> add append attributes docs

- 6.x/crud-fields.md
- 7.x-dev/crud-fields.md
Change the recommended way of defining the switch color to #hex and suggest the variable name developers can overwrite if they need more granular control, eg, assigning other `--var` they have in their application.
> fix switch docs

- 6.x/crud-filters.md
I didn't find any place where we had this documented, so here goes:
> add docs for `addClause()` and `addBaseClause()`

- 7.x-dev/crud-fields.md
- 7.x-dev/crud-uploaders.md
This PR changes the titles of our Uploader docs a little bit, to make them easier to understand... and introduces a new title that I consider important - HOW TO CREATE AN UPLOADER.
We don't have a guide for that right now. And I myself don't know how uploaders work. So I think it's important to add this bit of documentation, that explains... if you want to create an Uploader here's what you do... what rules you have to respect... and WHY. That will FORCE US to basically make Uploaders understandable, by anyone (including me 😅).
@pxpm can you please fill in this TODO with actual docs on how to create an Uploader. In the process, it will help me understand Uploaders and help me review the PRs we have in the pipeline.
> reorganize uploader docs

- 7.x-dev/crud-filters.md
- 7.x-dev/release-notes.md
fixes #623  - this requires https://github.com/Laravel-Backpack/PRO/pull/320 to be merged before for this to work.
Please @tabacitu add the following image in backpack website, and update this PR with the proper url before merging.
> docs for agnostic filters

- 7.x-dev/base-components.md
- 7.x-dev/base-widgets.md
- 7.x-dev/upgrade-guide.md
Add docs for the datatable widget
> Docs for the datatable widget

- 7.x-dev/base-widgets.md
- 7.x-dev/crud-chips.md
- 7.x-dev/index.md
This PR adds docs for the chip widget introduced in https://github.com/Laravel-Backpack/CRUD/pull/5815 and with demo examples in https://github.com/Laravel-Backpack/demo/pull/701
Documented:
Todo:
> add docs for chip widget

- 7.x-dev/upgrade-guide.md
When quickly checking out the v7 alpha for possible incompatibilities with my app (first look shows that it's running fine btw, keep up the good work!), I noticed that my local environment erred when trying to render views. Given that this originated from some basset call, I guessed that clearing bassets would solve the issue and it did. I think however that this warrants adding it as a recommended step to the migration guide.
> Add basset:clear to upgrade guide

- 6.x/base-how-to.md
- 7.x-dev/base-how-to.md
Some of the links to the Laravel documentation were referring back as far as Laravel v5.7 😱 
Updated those to evergreen links 😉
> Update links to laravel docs

- 7.x-dev/upgrade-guide.md
> update upgrade guide
