- 3.4/crud-operation-reorder.md
As answered in this StackOverflow question : https://stackoverflow.com/questions/40334901/what-are-the-reordering-columns-on-laravel-backpack/40361674#40361674
> Reorder : integer fields

- 3.4/add-ons-community.md
I think it's fair to link to and name the license more than "free" or "-".
> Named and Linked Licenses

- 3.4/crud-fields.md
This might save some people time, as per usual I just copied the documentation and the example was saving / renaming my png's to jpg's
> save uploaded image as jpg, don't just rename

- 3.4/crud-operation-reorder.md
I forgot to update the default values and nullable field last time.
> Details on reorder fields

- 3.5/upgrade-guide.md
I'm strongly against a massive `composer update`, especially in a production environment, as all the other librairies will also potentially be updated without prior checking.
> proposed composer install instead of composer update

- 3.5/crud-columns.md
Email column type was not documented so i went to create my own and when doing PR to CRUD was already there xD
> Email Column Documentation

- 3.5/crud-how-to.md
It helps me when I saw someone mention it in stackoverflow. So I think it's helpful so I add it here.
> Add few description to customize views.

- 3.6/crud-fields.md
Actually documentation don't mention the value option for select2
> add doc about default value for select2

- 3.6/getting-started-basics.md
> Grammar fix in getting-started-basics.md

- 3.6/crud-fields.md
> missing comma

- 4.0/crud-fields.md
Include that you can make temporary URL's for upload and upload multiple fields for files already on S3
> include extra parameter for upload fields

- 4.0/crud-columns.md
- 4.0/crud-fields.md
- 4.0/crud-filters.md
For the issue: https://github.com/Laravel-Backpack/Docs/issues/65
> For some examples code formatting is not consistent

- 4.0/base-how-to.md
fixed typo "tge UNIQUE" to "the UNIQUE" in base-how-to.md file
> fixed typo

- 4.0/crud-fields.md
In response to merging https://github.com/Laravel-Backpack/CRUD/pull/2261
> add sortable to browse_multiple field

- 4.0/crud-fields.md
> unused [/block] tags removed

- 4.0/base-widgets.md
It took me a while to figure it out
> Added example of Widget View name prefix for using ViewComposers

- 4.0/crud-fields.md
Show developers how they could remove any previous image from disk when uploading a new one.
> Update image upload example

- 4.1/crud-operation-fetch.md
replaced searchAttributes with search_attributes
> [4.1] update fetch docs

- 4.1/crud-fields.md
Fix does not need a description
> Removed not supported helper starts_with()

- 4.1/crud-fields.md
Fix does not need a description
> Removed some deprecated values in 4.1

- 4.0/add-ons-community.md
Removing old addons that would no longer work due to lack of maintenance on my part as well as adding new one.
> Updating my addons.

- 4.1/crud-operation-create.md
Related to https://github.com/Laravel-Backpack/CRUD/issues/2104
> Tabacitu patch 1

- 4.1/crud-save-actions.md
Related to https://github.com/Laravel-Backpack/CRUD/pull/2800.
> Add translation and button text instruction to crud-save-actions

- 4.1/crud-fields.md
Added `value` attribute to hidden field example.
> Update hidden field example

- 4.1/crud-columns.md
Just adding some padronization to string quotes. Had a problem with bulk search and replace because I copied from documentation without changing to a single standard.
> Using single quote stardard

- 4.1/getting-started-videos.md
- 4.1/index.md
- 4.1/introduction.md
This PR (finally) adds a way for first-timers to learn how to use Backpack by watching a few videos (31 min in total). In order for it to get merged, we first need to merge https://github.com/Laravel-Backpack/Generators/pull/84 - because inside the videos we do `php artisan backpack:build` and it generates CrudControllers with one line for each field/column needed, instead of `autoSetFromDb()`. 
---
You can see the videos here before this get merged:
- [Intro](https://vimeo.com/424693910/164ea1e6a6)
- [The Admin Interface - HTML & CSS](https://vimeo.com/424698837/f92f2012c4)
- [Generating and Understanding CRUDs](https://vimeo.com/424701595/a67b748d5a)
- [Using Operations and Features inside CRUDs](https://vimeo.com/424703257/f18b357684)
---
I'm a little disappointed about the quality - I …
> added video course for getting started

- 3.4/crud-columns.md
- 3.4/crud-fields.md
- 3.4/crud-filters.md
- 3.5/crud-columns.md
- 3.5/crud-fields.md
- 3.5/crud-filters.md
- 3.6/crud-columns.md
- 3.6/crud-fields.md
- 3.6/crud-filters.md
- 4.0/crud-buttons.md
- 4.0/crud-columns.md
- 4.0/crud-fields.md
- 4.0/crud-filters.md
- 4.1/crud-buttons.md
- 4.1/crud-columns.md
- 4.1/crud-fields.md
- 4.1/crud-filters.md
Made code formatting and comments in examples more consistent.
Also additional tweaks for the issue: #65
> For some examples code formatting is not consistent #66

- 4.1/crud-save-actions.md
> Update crud-save-actions.md - missing coma

- 4.1/add-ons-tutorial.md
> Fixed minor typo

- 4.1/crud-operation-update.md
Hi! First PR!
Change is so small I didn't consider creating a new branch for it. Should I?
Regards!
X.
> $this->crud->getRequest() instead of $this->crud->request

- 4.1/crud-fields.md
as a response to https://github.com/Laravel-Backpack/CRUD/issues/3065
> add details about how field attributes about relationships work

- 4.1/crud-fields.md
About https://github.com/Laravel-Backpack/CRUD/issues/3242
> Add info about CrudTrait for identifiableAttribute

- 4.1/crud-fields.md
The code has been taken from the [PackageManager code](https://github.com/Laravel-Backpack/PermissionManager/blob/master/src/app/Http/Controllers/UserCrudController.php#L103-L124) (as per linked in the docs).
> Update custom store operation method example

- 4.1/installation.md
update docs as mentioned by @iMokhles here https://github.com/Laravel-Backpack/CRUD/issues/3255#issuecomment-711159261
> fix typo change to Laravel 7+

- 4.1/crud-how-to.md
similar to https://backpackforlaravel.com/docs/4.1/crud-fields#optional-attributes-for-fields-containing-related-entries
> Returning $results

- 4.1/release-notes.md
It just a simple typo fixing in docs
> a simple typo fixed in release note

- 4.1/base-widgets.md
While testing Widgets, I had to go find the namespace of `Widget`, so I added it to docs for an easy access.
Ended up formatting code blocks 😅
> Added Widget namespace

- 4.1/base-about.md
fixes https://github.com/Laravel-Backpack/CRUD/issues/3405
> update which blade files get published upon installation

- 4.1/crud-columns.md
It was implicit, so I added just a small note.
> Added note for wrapper callbacks

- 4.1/upgrade-guide.md
Related with https://github.com/Laravel-Backpack/docs/issues/192
- Added a note for the revisions table.
- Added a diff with the changes to be applied to User model (CrudTrait and HasRoles).
> Updated upgrade-guide.md

- 4.1/installation.md
> Fixed manually-install-backpack link

- 4.1/crud-columns.md
Reverts Laravel-Backpack/docs#234
> Revert "Update crud-columns.md"

- 4.1/base-widgets.md
Small code typos in the example docs
> fix charts widget example typo

- 4.1/install-optionals.md
> Added FileManager Package

- 4.1/crud-fields.md
On GitHub https://github.com/ionaru/easy-markdown-editor section **About**
EasyMDE: A simple, beautiful, and embeddable JavaScript Markdown editor. Delightful editing for beginners and experts alike. Features built-in autosaving and spell checking.
https://easy-markdown-editor.tk/
> Outdated link

- 4.1/crud-fields.md
Docs counterpart for https://github.com/Laravel-Backpack/CRUD/pull/3798
> updated docs to be in sync with #3798

- 4.1/crud-fields.md
This is related to; https://github.com/Laravel-Backpack/CRUD/pull/3342
> Add line awesome font to icon picker docs

- 4.1/crud-columns.md
refs: https://github.com/Laravel-Backpack/CRUD/pull/3624
> Docs about visible in show accepting a closure.

- 4.1/installation.md
Related with https://github.com/Laravel-Backpack/CRUD/issues/3841.
> Added note about `--no-interaction` argument

- 4.2-dev/base-widgets.md
related to https://github.com/Laravel-Backpack/CRUD/pull/3912
> add docs for script and style widgets

- 4.2-dev/crud-how-to.md
- 4.2-dev/upgrade-guide.md
Provides docs and upgrade guide for https://github.com/Laravel-Backpack/CRUD/pull/3942
> add docs on removing operation CSS and JS files

- 4.2-dev/crud-columns.md
Related with https://github.com/Laravel-Backpack/CRUD/pull/3936.
> Deprecate closure column

- 4.2-dev/crud-fields.md
- 4.2-dev/upgrade-guide.md
docs for https://github.com/Laravel-Backpack/CRUD/pull/3905
> add docs for repeatable changes in 4.2

- 4.2-dev/release-notes.md
- 4.2-dev/upgrade-guide.md
Docs for https://github.com/Laravel-Backpack/CRUD/pull/2652
> docs for using loadonce directive

- 4.2-dev/upgrade-guide.md
docs for https://github.com/Laravel-Backpack/CRUD/pull/3955
> add doc for non-inputs being prefixed by underscore

- 4.2-dev/upgrade-guide.md
Docs if https://github.com/Laravel-Backpack/CRUD/pull/3986 gets merged
> upgrade guide after moving operation configs to separate files

- 4.2-dev/upgrade-guide.md
docs for https://github.com/Laravel-Backpack/CRUD/pull/3987
> docs for changing saveAllInputsExcept to strippedRequest

- 4.2-dev/upgrade-guide.md
Docs for https://github.com/Laravel-Backpack/CRUD/pull/3459
> move page_or_link field to menucrud

- 4.1/crud-fields.md
- 4.2-dev/crud-fields.md
this should follow https://github.com/Laravel-Backpack/CRUD/pull/3962
> Add docs for new relationship process

- 4.1/getting-started-basics.md
> Fix broken links

- 5.x/base-about.md
1- Add a route in custom.php.
2- Create a controller.
3- Create a blade template for respective page.
1- Create a controller.
2- Add a route in custom.php.
3- Create a blade template for respective page.
If we add route in `custom.php` before creating a controller it will throw an error on **step-2**, because we have added a route with controller in `custom.php` where added controller does not exists. So **step-2** fails with an error.
> Dynamic page creation steps are not in right sequence.

- 5.x/crud-operations.md
> wrong method name

- 5.x/crud-filters.md
@tabacitu, you'll probably want to move the image from `githubusercontent.com/...` to backpack server and change the path, or maybe this is ok 🤷‍♂️
Fixes https://github.com/Laravel-Backpack/docs/issues/312.
The image is this one;
> Added missing screenshot on simple filter

- 4.1/crud-fields.md
- 5.x/crud-fields.md
Fix for https://github.com/Laravel-Backpack/docs/issues/328.
Thank you @CharlieNH
> Typo fix deduce instead of deduct

- 5.x/crud-fields.md
Fix for https://github.com/Laravel-Backpack/docs/issues/294
> Documentation on `upload_multiple` field validation

- 5.x/crud-operation-fetch.md
goes with the PR https://github.com/DigitallyHappy/backpack-pro/pull/33
> add searchOperator configuration to Fetch

- 5.x/crud-fields-javascript-api.md
- 5.x/crud-fields.md
- 5.x/index.md
> 5.1 - add docs about CrudField JS API

- 5.x/crud-operation-create.md
After we merged https://github.com/Laravel-Backpack/CRUD/pull/4220 this step is not necessary anymore. 
hurra \o
> update docs, remove unecessary setValidation call.

- 5.x/crud-fields.md
This new updated version of the mutator allow developers to use it on translatable fields too. 
This was reported here: https://github.com/Laravel-Backpack/CRUD/issues/4395
> make mutator with translatable attributes too

- 5.x/crud-fields.md
Documentation for https://github.com/Laravel-Backpack/CRUD/pull/4463.
It's mainly a copy of checkbox, should look something like;
@tabacitu you'll probably want to move the image to `https://backpackforlaravel.com/uploads/docs-5-x/fields/switch.png`
> Added switch field

- 5.x/crud-fields.md
name says it all!
We are still working on possible solutions/workarounds, but ... it's not like 1+1=2!
This should be merged asap if everything ok, we later update with more info regarding our direction on that issue.
> add week and month browser support notices

- 5.x/crud-filters.md
add example to docs on how to configure filter options.
> show how to configure filter attributes

- 5.x/crud-fields.md
docs for: https://github.com/Laravel-Backpack/CRUD/pull/4625
> add note about optional wrapper

- 5.x/base-widgets.md
- 5.x/crud-columns.md
- 5.x/crud-fields.md
- 5.x/crud-how-to.md
- 5.x/crud-operation-clone.md
- 5.x/crud-operation-delete.md
- 5.x/crud-operation-reorder.md
This is a fix for https://github.com/Laravel-Backpack/CRUD/issues/4658.
New commands allow to publish views from pro.
> Replaced old publish commands with the new ones

- 5.x/crud-fields.md
- 5.x/crud-how-to.md
still need polish, is here for now to help us settle some details.
> morphto relationship field docs

- 5.x/crud-columns.md
- 5.x/crud-fields.md
This are the docs for https://github.com/Laravel-Backpack/CRUD/pull/4678
> add enum docs

- 5.x/crud-fields.md
docs for https://github.com/Laravel-Backpack/CRUD/pull/4742
> add docs about fileName in uploadFileToDisk

- 5.x/crud-fields.md
Documentation to work with new phone field in https://github.com/Laravel-Backpack/PRO/pull/103
> Phone field documentation

- 5.x/crud-fields.md
Fix options example on docs, because in "onlyCountries" list is not "cl" so if people copy/paste example will not work.
> Fix options example

- 5.x/crud-columns.md
closes https://github.com/Laravel-Backpack/CRUD/issues/4838
> add orderLogic example to relationship_count column

- 5.x/generating-code.md
- 5.x/index.md
While working on the Hero Video, I realized we do NOT have a page to describe our CLI commands, nor DevTools. That's a huge oversight, so I sat down and created it.
Now... this does need a double-check... so please @pxpm , @jorgetwgroup , @maurohmartinez or @phpfour - if you can, give this a quick read and suggest improvements. I am, however, merging this ASAP, because I need to shoot my screen using it... 🤷‍♂️😅
> add page about generating code using CLI or DevTools

- 5.x/crud-operation-list-entries.md
Hello,
It took me some time to figure how to change field separator in datatable. (comma to semicolon)
I hope this is the right place to share it.
> add example Custom dataTableConfiguration

- 5.x/crud-operation-trash.md
- 5.x/index.md
Document for Trash & BulkTrash operation
> Document for Trash & BulkTrash operation

- 5.x/crud-operation-update.md
Add missing Install requirement to add a Slug package.
> Add missing Install requirement to install `cviebrock/eloquent-sluggable`

- 5.x/crud-fields-javascript-api.md
Added an example to document the use case outlined in https://github.com/Laravel-Backpack/community-forum/issues/422
> added example 12

- 5.x/crud-operation-create.md
- 5.x/crud-operation-list-entries.md
- 5.x/crud-operation-reorder.md
- 5.x/crud-operation-show.md
- 5.x/crud-operation-update.md
#385 
Documented “How to add custom sections(aka. Widgets)” inside following operations:
- list
- create
- update
- show
- reorder
> Widget Section for Operations

- 5.x/crud-operation-list-entries.md
fixes https://github.com/Laravel-Backpack/CRUD/issues/1235
> add note about debugging ajax requests

- 5.x/crud-operation-update.md
This is to add changes introduced by this [PR](https://github.com/Laravel-Backpack/CRUD/pull/4813).
> [Feature Request] Allow delete button on edit page

- 5.x/crud-operation-show.md
- 6.x/crud-operation-show.md
docs for PR https://github.com/Laravel-Backpack/CRUD/pull/5043
> docs v5 and v6 for show operation tabs

- 6.x/crud-fields.md
- 6.x/custom-validation-rules.md
docs for https://github.com/Laravel-Backpack/PRO/pull/125 including uploader and validation.
> [v6] add dropzone docs

- 6.x/release-notes.md
> add v6 release notes

- 6.x/crud-fields.md
Docs for https://github.com/Laravel-Backpack/CRUD/pull/5080 
https://github.com/Laravel-Backpack/PRO/pull/157
> change date range and checklist docs

- 6.x/crud-fields.md
removed field in https://github.com/Laravel-Backpack/PRO/pull/159
> remove address algolia field

- 6.x/crud-columns.md
> Add v6 columns to the docs.

- 4.1/crud-fields.md
- 5.x/crud-fields.md
- 6.x/crud-fields.md
Fix old broken link of Easy MDE, this is the issue: https://github.com/orgs/Laravel-Backpack/projects/13/views/21?pane=issue&itemId=27939948
> Fix old link

- 6.x/base-components.md
- 6.x/crud-tutorial.md
- 6.x/index.md
- 6.x/upgrade-guide.md
Adds docs for https://github.com/Laravel-Backpack/CRUD/pull/5135/
> add docs for menu components in v6

- 6.x/getting-started-videos.md
the ones Mauro created 🎉🙏
Note that this is incomplete - we should still do https://github.com/Laravel-Backpack/docs/issues/442 but that'll take too much time for me right now.
> add new videos to v6 docs

- 6.x/add-ons-tutorial-how-to-create-a-theme.md
- 6.x/index.md
Addresses https://github.com/Laravel-Backpack/docs/issues/417
> add docs on how to create a new backpack theme

- 6.x/crud-columns.md
- 6.x/crud-fields.md
- 6.x/release-notes.md
- 6.x/upgrade-guide.md
regarding: https://github.com/Laravel-Backpack/PRO/issues/122
- added to upgrade guide
- added to release notes
- remove field and column mentions
> remove color picker from docs

- 6.x/getting-started-videos.md
> Put Links & Description to Videos docs page

- 6.x/base-how-to.md
Add note about locale change, and github repo.
https://github.com/Laravel-Backpack/docs/issues/453
> add note about locale changing

- 6.x/base-about.md
It is acceptable to refer to an "admin" with "their" and in fact in the second part of the sentence "they" is used to refer to the "admin"
> Make pronouns consistent

- 6.x/crud-fields.md
at the moment they are not available.
> remove lineawesome from icon picker

- 6.x/getting-started-basics.md
This updates the URL to the Laracasts "Laravel from Scratch" series to point to the latest version.
> Update Laracasts series URL

- 6.x/crud-fields.md
Solves #465 
In https://github.com/Laravel-Backpack/community-forum/issues/559#issuecomment-1630673757 Antonio has outlined the process. Now let's think... where do we document it?
inside the field? it's too big for that;
inside the FAQ? too hidden;
inside a blog post? maybe; but still too hidden;
So how about... **we just mention it in the field docs, and link to the issue on GitHub**? That should be a good middle option, right? It's right where people expect it (field docs), it can be as long as possible, and it's already written.
> How to add custom plugins to CKEditor in Backpack v6

- 6.x/install-optionals.md
**Solves** https://github.com/Laravel-Backpack/LogManager/issues/64 for docs
**How**
Replace old command with the new command
> Need to update menu-item instruction for Optional Packages as per v6

- 6.x/crud-fields.md
> add more examples for pivot select

- 6.x/crud-fields-javascript-api.md
fixes https://github.com/Laravel-Backpack/CRUD/issues/5292
> add morphable example to crudfield api docs

- 6.x/crud-buttons.md
- 6.x/crud-cheat-sheet.md
- 6.x/crud-operations.md
This adds documentation for https://github.com/Laravel-Backpack/CRUD/pull/5335
> add docs for setAccessCondition

- 6.x/crud-columns.md
docs for https://github.com/Laravel-Backpack/CRUD/pull/5317
> docs for columns `linkTo` helper

- 6.x/crud-buttons.md
Solves https://github.com/Laravel-Backpack/community-forum/issues/770
Users were facing button visibility/access issue, Assuming it not working.
> Quick button access implementation

- 6.x/base-how-to.md
Solves: https://github.com/Laravel-Backpack/docs/issues/524
> Overwrite register.blade.php instructions are wrong

- 6.x/crud-columns.md
https://github.com/Laravel-Backpack/CRUD/pull/5383
https://github.com/Laravel-Backpack/CRUD/pull/5384
> Added linkToShow and linkTarget documentation

- 6.x/crud-api.md
https://github.com/Laravel-Backpack/CRUD/pull/5390
https://github.com/Laravel-Backpack/CRUD/pull/5391
> Added allowAccessOnlyTo and denyAllAccess documentation

- 6.x/crud-operations.md
fixes https://github.com/Laravel-Backpack/CRUD/issues/5410
> add example of entry based access

- 6.x/crud-fields.md
The website domain extension is wrong, i receive this from this issue: https://github.com/Laravel-Backpack/community-forum/issues/788
> The website is https://mattstauffer.com not https://mattstauffer.co

- 6.x/crud-operation-inline-create.md
add example on how to add an inline widget
> add widget ->inline example

- 6.x/crud-fields.md
docs for https://github.com/Laravel-Backpack/PRO/pull/223
> Add docs for slug library

- 6.x/crud-operation-list-entries.md
This is the docs for https://github.com/Laravel-Backpack/PRO/pull/218.
> Add docs for custom views

- 6.x/crud-operation-list-entries.md
Heads-up @promatik I felt the need to update the docs because:
- it wasn't obvious to me what the benefit is for the admin;
- we were not showing how it looks (an image is worth 1000 words);
If you need to edit further or I made any mistake, please correct.
> rephrase custom-views docs

- 6.x/crud-operation-create.md
fixes https://github.com/Laravel-Backpack/CRUD/issues/5435
> add notice for model events in fields

- 4.1/base-widgets.md
- 5.x/base-widgets.md
- 6.x/base-widgets.md
Fixing [this issue](https://github.com/Laravel-Backpack/community-forum/issues/857) updating the url.
Cheers.
> FIx broken url

- 6.x/release-notes.md
Fix demo URL, thanks to this issue https://github.com/Laravel-Backpack/community-forum/discussions/510
> Fix demo URL

- 6.x/getting-started-license-and-support.md
Fix typos and make minor edits.
"... we can give you" sounds a little odd.
"use case" is not hyphenated, you use both versions here.
> Fix typos and make minor edits

- 6.x/base-widgets.md
This is the companion PR to https://github.com/Laravel-Backpack/CRUD/pull/5510
> add heading class and content class options

- 6.x/crud-fields.md
cleanup select2 json api docs.
> cleanup select2 from json

- 6.x/crud-fields.md
This adds updated docs for CKEditor
- how to use elfinder
- how to use custom builds
> update ckeditor docs

- 6.x/crud-buttons.md
Docs for
https://github.com/Laravel-Backpack/CRUD/pull/5512
> Docs for Quick Ajax Button

- 6.x/crud-fields.md
This are the docs for https://github.com/Laravel-Backpack/CRUD/pull/5538
Instructs developers how the can enable the selection of duplicated pivots in ToMany relations.
> add docs on how to allow the selection of multiple pivots

- 6.x/crud-fields.md
This are the docs for https://github.com/Laravel-Backpack/CRUD/pull/5559
> add "select all" option to checklist field

- 6.x/crud-api.md
- 6.x/crud-operation-list-entries.md
docs for: https://github.com/Laravel-Backpack/CRUD/pull/5651
> Add set query() method to api

- 6.x/crud-columns.md
docs for: https://github.com/Laravel-Backpack/CRUD/pull/5670
> update url column docs

- 6.x/crud-operation-clone.md
docs for: https://github.com/Laravel-Backpack/PRO/pull/283
> add redirect after clone option

- 6.x/crud-columns.md
docs for https://github.com/Laravel-Backpack/CRUD/pull/5680
> add separator to select_multiple column

- 6.x/add-ons-tutorial-how-to-create-a-theme.md
- 7.x-dev/add-ons-tutorial-how-to-create-a-theme.md
fixes: https://github.com/Laravel-Backpack/CRUD/issues/5694
mentioning a function that doesn't exist 🤷‍♂️
> remove inexistent function

- 7.x-dev/crud-columns.md
docs for https://github.com/Laravel-Backpack/CRUD/pull/5845
> update json column docs
